--- # standard header for yaml
- hosts: webservers # the name must defined at main ansible conf file at /etc/ansible
  become: yes
  become_method: sudo
  tasks:
    - name: Add Epel repository
      yum:
        name: epel-release
        state: present

    - name: install nginx
      yum:
        name: nginx
        state: absent
...
