# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jk|
    jk.vm.box='ebracho/jenkins'
    jk.vm.hostname='jenkins'
    jk.vm.network "private_network", ip: '10.0.10.103'
    jk.vm.network "forwarded_port", guest:8080, host:80
  end



end
