# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ansible" do |ansible|
    ansible.vm.box='generic/fedora28'
    ansible.vm.hostname='ansible'
    ansible.vm.network "private_network", ip: '10.0.10.100'
  end
  config.vm.define "web" do |web|
   web.vm.box='centos/7'
   web.vm.hostname='web'
   web.vm.network "private_network", ip: '10.0.10.101'
   web.vm.network "forwarded_port", guest: 80, host: 8080
  end
 config.vm.define "web2" do |web2|
   web2.vm.box='centos/7'
   web2.vm.hostname='web2'
   web2.vm.network "private_network", ip: '10.0.10.103'
   web2.vm.network "forwarded_port", guest: 80, host: 8081
  end
 config.vm.define "web3" do |web3|
   web3.vm.box='centos/7'
   web3.vm.hostname='web3'
   web3.vm.network "private_network", ip: '10.0.10.105'
   web3.vm.network "forwarded_port", guest: 80, host: 8082
  end
  config.vm.define "db" do |db|
    db.vm.box='debian/jessie64'
    db.vm.hostname='db'
    db.vm.network "private_network", ip: '10.0.10.102'
  end

config.vm.define "lbo" do |lbo|
    lbo.vm.box='debian/jessie64'
    lbo.vm.hostname='lbo'
    lbo.vm.network "private_network", ip: '10.0.10.110'
  end
end
