# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 # config.vm.define "ansible" do |ansible|
 #   ansible.vm.box='generic/fedora28'
 #   ansible.vm.hostname='ansible'
 #   ansible.vm.network "private_network", ip: '10.0.10.100'
 # end
 # config.vm.define "web" do |web|
 #   web.vm.box='centos/7'
 #   web.vm.hostname='web'
 #   web.vm.network "private_network", ip: '10.0.10.101'
 # end
 # config.vm.define "db" do |db|
 #   db.vm.box='debian/jessie64'
 #   db.vm.hostname='db'
 #   db.vm.network "private_network", ip: '10.0.10.102'
 # end

#  config.vm.define "jenkins" do |jk|
#    jk.vm.box='ebracho/jenkins'
#    jk.vm.hostname='jenkins'
#    jk.vm.network "private_network", ip: '10.0.10.103'
#    jk.vm.network "forwarded_port", guest:80, host:8080
#  end
# config.vm.define "openstack" do |os|
#	os.vm.box = "openstack-user/precise-grizzly"
#	os.vm.hostname = 'openstack'
#	os.vm.network "private_network", ip: '10.0.10.104'
#	end


  config.vm.define "suse" do |suse|
    suse.vm.box='suse/sles12sp1'
    suse.vm.hostname='suse12'
    suse.vm.network "private_network", ip: '10.0.10.106'
  end
 config.vm.define "rhel" do |rhel|
    rhel.vm.box='iamseth/rhel-7.3'
    rhel.vm.hostname='suse'
    rhel.vm.network "private_network", ip: '10.0.10.107'
  end
config.vm.define "deb" do |deb|
    deb.vm.box='debian/jessie64'
    deb.vm.hostname='deb'
    deb.vm.network "private_network", ip: '10.0.10.108'
  end
config.vm.define "centos" do |centos|
    centos.vm.box='centos/7'
    centos.vm.hostname='centos7'
    centos.vm.network "private_network", ip: '10.0.10.109'
  end
config.vm.define "fedora" do |fed|
    fed.vm.box='generic/fedora28'
    fed.vm.hostname='fedora28'
    fed.vm.network "private_network", ip: '10.0.10.110'
  end
config.vm.define "arch" do |arch|
    arch.vm.box='generic/arch'
    arch.vm.hostname='archlinux'
    arch.vm.network "private_network", ip: '10.0.10.111'
  end
config.vm.define "oracle" do |oracle|
    oracle.vm.box='generic/oracle7'
    oracle.vm.hostname='oraclelinux'
    oracle.vm.network "private_network", ip: '10.0.10.112'
  end


end
